theme: jekyll-theme-minimal
title: Seohee's Portfolio
description: "Welcome to my portfolio! This is a collection of my work and experiences."
url: "https://creative-seohee.github.io"
google_analytics: G-DXKJ0EC3PM